/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtualpet;

import java.util.Scanner;

public class VirtualPetApp {
    public static void main(String[] args) {
        int game;
        Scanner input = new Scanner(System.in);
        System.out.println("Who is the best little puppy ever?! (Enter puppy's name)");
        String puppyName = input.nextLine();

        Pet dog = new Pet(puppyName);
        petMenu = (puppyName);

        do {
            System.out.println("What are we doing today?");
            System.out.println("1. Feed " + puppyName + " some yummy treats.");
            System.out.println("2. Give " + puppyName + " fresh water.");
            System.out.println("3. Take " + puppyName + " for a walk.");
            System.out.println("4. Take " + puppyName + " to the Vet.");
            System.out.println("5. Play with " + puppyName + ".");

            //select options 
            game = input.nextInt();

            if(game == 5) {
                continue;
            }

            //feeding the puppy
            else if(game == 1) {
                if(dog.getHunger() > 5) {
                    System.out.println("");
                }
            }
        }
    }
}
